version: '3.3'
services:
  mysql:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: 'userdb'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      timeout: 10s
      retries: 5    
  web:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: "jdbc:mysql://mysql:3306/userdb?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10"
      DB_USER: 'root'
      DB_PASSWORD: 'password'    
    links:
      - mysql
